raspimouse:
  ros__parameters:
    odometry_scale_left_wheel : 1.0
    odometry_scale_right_wheel: 1.0
    use_light_sensors         : false
    use_pulse_counters        : true
    wheel_diameter            : 0.200  # meters
    wheel_tread               : 0.350 # meters
    pulses_per_revolution     : 1120.4 #524.9
    light_sensors_hz          : 100.0
    odom_hz                   : 200.0
    switches_hz               : 10.0
    initial_motor_power       : true
    odom_frame_id             : "odom"
    odom_child_frame_id       : "base_footprint"
    odom_frame_prefix         : ""
